import { useEffect, useRef, useState } from "react";
import maplibregl from "maplibre-gl";
import { MapboxOverlay } from "@deck.gl/mapbox";
import { ScatterplotLayer } from "@deck.gl/layers";
import type { AccountMapPinDto, LocationRecordMapPinDto } from "@pulse-brazil/application";
import { clientTypeColorVar, primaryClientType } from "../../utils/clientType";
import "./BrazilMap.css";

interface BrazilMapProps {
  pins: AccountMapPinDto[];
  locationPins?: LocationRecordMapPinDto[];
  selectedAccountId: string | null;
  onSelectAccount?: (accountId: string) => void;
  onSelectLocationPin?: (pin: LocationRecordMapPinDto) => void;
}

// One fixed color per LocationRecordKind — deliberately distinct from
// --color-primary/--color-client-* (account client-type pins use those), so
// an Office pin is never the same color as an account pin and the two
// marker families read as clearly different things.
const LOCATION_KIND_COLOR_VAR: Record<string, string> = {
  Office: "--color-location-office",
  Event: "--color-location-event",
  Visit: "--color-location-visit",
  SignalLocation: "--color-text-muted",
  Other: "--color-text-faint",
};

const SELECTED_ZOOM = 7;

// Brazil's real extent (mainland + offshore islands like Fernando de
// Noronha), used to fit the initial view — a fixed zoom level instead
// showed more or less of the country depending on how much pixel height the
// surrounding layout left for the map, which is exactly what cropped Brazil
// out of frame once the Command Centre header/KPI strip took space above it.
const BRAZIL_BOUNDS: [[number, number], [number, number]] = [
  [-74, -34],
  [-29, 6],
];

// OpenFreeMap: free, keyless vector tiles for MapLibre GL JS — no account,
// no API token, no usage limits. "positron" is a clean light/muted style,
// matching Soft Quartz's calm aesthetic better than a busier default style.
const MAP_STYLE_URL = "https://tiles.openfreemap.org/styles/positron";

// Generated by scripts/generate-map-data.ts. Positron has no per-country
// admin-0 layer to key off, so Brazil's high-resolution boundary here feeds
// a thin outline layer rather than a paint-property override. Earlier this
// also drove a full-country fill wash (Brazil/LATAM/world tiers) — dropped:
// with only Brazil ever on screen, a green fill added no information and
// competed for attention with the pins actually meant to be read.
const COUNTRY_TIERS_URL = "/data/world-countries-tiers.geojson";

// deck.gl layers need numeric colors, not CSS var() strings. Read the tokens
// straight off the document so this stays in sync with tokens.css — including
// its dark-mode redeclarations — instead of duplicating hex values here.
function cssColor(varName: string): [number, number, number] {
  const hex = getComputedStyle(document.documentElement).getPropertyValue(varName).trim();
  const n = Number.parseInt(hex.replace("#", ""), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

interface HoveredPin {
  name: string;
  x: number;
  y: number;
}

export function BrazilMap({ pins, locationPins = [], selectedAccountId, onSelectAccount, onSelectLocationPin }: BrazilMapProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<maplibregl.Map | null>(null);
  const overlayRef = useRef<MapboxOverlay | null>(null);
  const [hoveredPin, setHoveredPin] = useState<HoveredPin | null>(null);

  const onSelectAccountRef = useRef(onSelectAccount);
  onSelectAccountRef.current = onSelectAccount;
  const onSelectLocationPinRef = useRef(onSelectLocationPin);
  onSelectLocationPinRef.current = onSelectLocationPin;

  useEffect(() => {
    if (!containerRef.current) return;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: MAP_STYLE_URL,
      bounds: BRAZIL_BOUNDS,
      fitBoundsOptions: { padding: 24 },
    });
    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-left");

    // Non-interleaved: deck.gl renders pins in its own canvas layered on top
    // of the map, rather than sharing MapLibre's WebGL context/state. These
    // are flat 2D dots with no need to interleave with 3D map geometry, and
    // interleaved mode was observed to corrupt MapLibre's own render state
    // (the base style stopped painting entirely) with this maplibre-gl/
    // deck.gl version pairing.
    const overlay = new MapboxOverlay({ interleaved: false, layers: [] });
    map.addControl(overlay);
    overlayRef.current = overlay;
    mapRef.current = map;

    map.on("load", () => {
      map.addSource("country-tiers", { type: "geojson", data: COUNTRY_TIERS_URL });

      // A thick, dark, fully-opaque border — deliberately fixed rather than
      // theme-reactive (stays dark in both light and dark mode) so Brazil
      // reads as clearly separated from its neighbors without needing to
      // mask/shade the rest of the map.
      map.addLayer({
        id: "brazil-outline",
        type: "line",
        source: "country-tiers",
        filter: ["==", ["get", "tier"], "brazil"],
        paint: {
          "line-color": "#0d1418",
          "line-width": 3.5,
          "line-opacity": 1,
        },
      });
    });

    // MapLibre doesn't detect CSS-driven container resizes on its own (e.g.
    // the signal feed collapsing/expanding changes this container's width
    // via a flex layout) — without this the canvas stays the old size and
    // visibly misaligns until the window itself is resized.
    const resizeObserver = new ResizeObserver(() => map.resize());
    resizeObserver.observe(containerRef.current);

    return () => {
      resizeObserver.disconnect();
      map.remove();
      mapRef.current = null;
      overlayRef.current = null;
    };
  }, []);

  // Account-node pins, rendered via deck.gl instead of DOM markers, colored
  // by the account's primary ClientType rather than temperature.
  useEffect(() => {
    const overlay = overlayRef.current;
    if (!overlay) return;

    // A dark shadow ring behind every dot, not a light one — the basemap
    // is a light neutral (no more green fill wash), so a light halo barely
    // shows up against it. A dark ring reads clearly against light map
    // surfaces regardless of what's underneath, which a same-tone halo
    // can't guarantee.
    const shadowColor = cssColor("--color-text");
    const accountShadow = new ScatterplotLayer<AccountMapPinDto>({
      id: "account-pins-shadow",
      data: pins,
      filled: true,
      stroked: false,
      radiusUnits: "pixels",
      getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
      getRadius: 14,
      getFillColor: [...shadowColor, 200],
    });

    const base = new ScatterplotLayer<AccountMapPinDto>({
      id: "account-pins",
      data: pins,
      pickable: true,
      stroked: true,
      filled: true,
      radiusUnits: "pixels",
      lineWidthUnits: "pixels",
      getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
      getRadius: 10,
      getFillColor: (pin) => cssColor(clientTypeColorVar(primaryClientType(pin.clientTypes))),
      getLineColor: (pin) => (pin.id === selectedAccountId ? cssColor("--color-primary-active") : cssColor("--color-surface")),
      getLineWidth: (pin) => (pin.id === selectedAccountId ? 3 : 2),
      onClick: (info) => {
        if (info.object) onSelectAccountRef.current?.(info.object.id);
      },
      onHover: (info) => {
        setHoveredPin(info.object ? { name: info.object.name, x: info.x, y: info.y } : null);
      },
      updateTriggers: {
        getLineColor: selectedAccountId,
        getLineWidth: selectedAccountId,
      },
    });

    // Office/Event/Visit/SignalLocation records — a separate marker family
    // from account client-type pins (fixed per-kind color, not client-type
    // color), so the two are never visually confused.
    // reviewStatus drives opacity directly from the DTO the backend sent —
    // the frontend never decides on its own whether a record is trustworthy.
    const locationShadow = new ScatterplotLayer<LocationRecordMapPinDto>({
      id: "location-record-pins-shadow",
      data: locationPins,
      filled: true,
      stroked: false,
      radiusUnits: "pixels",
      getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
      getRadius: 12,
      getFillColor: [...shadowColor, 200],
    });

    const locationMarkers = new ScatterplotLayer<LocationRecordMapPinDto>({
      id: "location-record-pins",
      data: locationPins,
      pickable: true,
      filled: true,
      stroked: true,
      radiusUnits: "pixels",
      lineWidthUnits: "pixels",
      getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
      getRadius: 8,
      getFillColor: (pin) => {
        const [r, g, b] = cssColor(LOCATION_KIND_COLOR_VAR[pin.kind] ?? "--color-text-faint");
        return [r, g, b, pin.reviewStatus === "ReviewRequired" ? 150 : 255];
      },
      getLineColor: [...cssColor("--color-surface"), 255],
      getLineWidth: 2,
      onClick: (info) => {
        if (info.object) onSelectLocationPinRef.current?.(info.object);
      },
    });

    overlay.setProps({ layers: [accountShadow, locationShadow, base, locationMarkers] });
  }, [pins, locationPins, selectedAccountId]);

  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    const pin = pins.find((p) => p.id === selectedAccountId);
    if (!pin) return;

    map.flyTo({
      center: [pin.coordinate.longitude, pin.coordinate.latitude],
      zoom: SELECTED_ZOOM,
      duration: 1200,
      essential: true,
    });
  }, [selectedAccountId, pins]);

  return (
    <div className="brazil-map">
      <div ref={containerRef} className="brazil-map__canvas" />
      {hoveredPin && (
        <div className="brazil-map__pin-tooltip" style={{ left: hoveredPin.x, top: hoveredPin.y }}>
          {hoveredPin.name}
        </div>
      )}
      {/* deck.gl renders pins to canvas, which isn't natively focusable/
          screen-reader-accessible. This mirrors the same click behavior as a
          real, tabbable, always-in-the-DOM control per pin — hidden until
          focused so it doesn't visually duplicate the canvas dots. */}
      <div className="brazil-map__a11y-pins">
        {pins.map((pin) => (
          <button
            key={pin.id}
            type="button"
            className="brazil-map__a11y-pin"
            aria-label={pin.name}
            aria-pressed={pin.id === selectedAccountId}
            onClick={() => onSelectAccount?.(pin.id)}
          >
            {pin.name}
          </button>
        ))}
        {locationPins.map((pin) => (
          <button
            key={pin.id}
            type="button"
            className="brazil-map__a11y-pin"
            aria-label={`${pin.label} (${pin.kind})`}
            onClick={() => onSelectLocationPin?.(pin)}
          >
            {pin.label}
          </button>
        ))}
      </div>
    </div>
  );
}
