import { useEffect, useRef, useState } from "react";
import maplibregl from "maplibre-gl";
import { MapboxOverlay } from "@deck.gl/mapbox";
import { ScatterplotLayer } from "@deck.gl/layers";
import type { AccountMapPinDto } from "@pulse-brazil/application";
import { Brazil3D } from "./Brazil3D";
import "./BrazilMap.css";

interface BrazilMapProps {
  pins: AccountMapPinDto[];
  selectedAccountId: string | null;
  onSelectAccount?: (accountId: string) => void;
}

const BRAZIL_CENTER: [number, number] = [-51.9253, -14.235];
const BRAZIL_ZOOM = 3.6;
const SELECTED_ZOOM = 7;

// OpenFreeMap: free, keyless vector tiles for MapLibre GL JS — no account,
// no API token, no usage limits. "positron" is a clean light/muted style,
// matching Soft Quartz's calm aesthetic better than a busier default style.
const MAP_STYLE_URL = "https://tiles.openfreemap.org/styles/positron";

// Generated by scripts/generate-map-data.ts — every country tagged brazil /
// latam / world. Positron has no per-country admin-0 fill layer to override
// directly (country color there comes from a single generic landcover fill),
// so the three-tier system is a layer-insertion fallback: this source feeds
// three stacked fill layers instead of a paint-property override.
const COUNTRY_TIERS_URL = "/data/world-countries-tiers.geojson";

const TEMP_BAND_VAR: Record<string, string> = {
  Hot: "--color-temp-hot",
  Warm: "--color-temp-warm",
  Cool: "--color-temp-cool",
  Cold: "--color-temp-cold",
};

// deck.gl layers need numeric colors, not CSS var() strings. Read the tokens
// straight off the document so this stays in sync with tokens.css — including
// its dark-mode redeclarations — instead of duplicating hex values here.
function cssColor(varName: string): [number, number, number] {
  const hex = getComputedStyle(document.documentElement).getPropertyValue(varName).trim();
  const n = Number.parseInt(hex.replace("#", ""), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function cssOpacity(varName: string): number {
  const raw = getComputedStyle(document.documentElement).getPropertyValue(varName).trim();
  const n = Number.parseFloat(raw);
  return Number.isFinite(n) ? n : 1;
}

export function BrazilMap({ pins, selectedAccountId, onSelectAccount }: BrazilMapProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<maplibregl.Map | null>(null);
  const overlayRef = useRef<MapboxOverlay | null>(null);

  const onSelectAccountRef = useRef(onSelectAccount);
  onSelectAccountRef.current = onSelectAccount;

  // Holding Ctrl swaps the flat 2D map for an isolated, freely-rotating 3D
  // relief model of Brazil (real elevation, masked to the actual coastline —
  // see Brazil3D.tsx). The 3D layer stays mounted after its first activation
  // so repeated toggling doesn't re-fetch terrain tiles every time; only its
  // visibility fades.
  const [is3D, setIs3D] = useState(false);
  const [has3DLoaded, setHas3DLoaded] = useState(false);

  useEffect(() => {
    if (is3D) setHas3DLoaded(true);
  }, [is3D]);

  useEffect(() => {
    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Control") setIs3D(true);
    }
    function handleKeyUp(event: KeyboardEvent) {
      if (event.key === "Control") setIs3D(false);
    }
    // Safety net: if focus leaves the window while Ctrl is held (e.g. a
    // Ctrl+Tab app switch), the keyup never fires here — reset on blur so
    // the 3D view doesn't get stuck on.
    function handleBlur() {
      setIs3D(false);
    }
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    window.addEventListener("blur", handleBlur);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
      window.removeEventListener("blur", handleBlur);
    };
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: MAP_STYLE_URL,
      center: BRAZIL_CENTER,
      zoom: BRAZIL_ZOOM,
    });
    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-left");

    // Non-interleaved: deck.gl renders pins in its own canvas layered on top
    // of the map, rather than sharing MapLibre's WebGL context/state. These
    // are flat 2D dots with no need to interleave with 3D map geometry, and
    // interleaved mode was observed to corrupt MapLibre's own render state
    // (the base style stopped painting entirely) with this maplibre-gl/
    // deck.gl version pairing.
    const overlay = new MapboxOverlay({ interleaved: false, layers: [] });
    map.addControl(overlay);
    overlayRef.current = overlay;
    mapRef.current = map;

    map.on("load", () => {
      map.addSource("country-tiers", { type: "geojson", data: COUNTRY_TIERS_URL });

      // Insert directly above the style's base background fill and below
      // everything else (water, boundaries, roads, labels) so place names
      // and borders stay legible on top while the tier fills still read as
      // the dominant color story underneath. addLayer's beforeId inserts
      // *underneath* that layer, so we target the *second* style layer
      // (the one right after "background") — targeting "background" itself
      // would insert our fills below it, letting its own paint color cover
      // them entirely.
      const firstLayerId = map.getStyle().layers?.[1]?.id;

      const worldColor = cssColor("--color-map-world");
      const latamColor = cssColor("--color-map-latam");
      const brazilColor = cssColor("--color-map-brazil");
      const latamOpacity = cssOpacity("--color-map-latam-opacity");
      const worldOpacity = cssOpacity("--color-map-world-opacity");

      // Country fills read as the "dominant color story" at country/continent
      // zoom, but a flat full-opacity fill at street level just paints over
      // roads and cities — it looks like broken rendering, not design. Each
      // layer fades out over zoom instead of holding one opacity everywhere.
      // LATAM/world are "context" and recede first; Brazil (the identity
      // color) fades further but never all the way to invisible.
      map.addLayer(
        {
          id: "world-massing",
          type: "fill",
          source: "country-tiers",
          filter: ["==", ["get", "tier"], "world"],
          paint: {
            "fill-color": `rgb(${worldColor.join(",")})`,
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 3, worldOpacity, 6, 0],
          },
        },
        firstLayerId,
      );
      map.addLayer(
        {
          id: "latam-secondary",
          type: "fill",
          source: "country-tiers",
          filter: ["==", ["get", "tier"], "latam"],
          paint: {
            "fill-color": `rgb(${latamColor.join(",")})`,
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 3, latamOpacity, 7, 0],
          },
        },
        firstLayerId,
      );
      map.addLayer(
        {
          id: "brazil-primary",
          type: "fill",
          source: "country-tiers",
          filter: ["==", ["get", "tier"], "brazil"],
          paint: {
            "fill-color": `rgb(${brazilColor.join(",")})`,
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 3, 1, 6, 0.5, 9, 0.12],
          },
        },
        firstLayerId,
      );
    });

    // MapLibre doesn't detect CSS-driven container resizes on its own (e.g.
    // the signal feed collapsing/expanding changes this container's width
    // via a flex layout) — without this the canvas stays the old size and
    // visibly misaligns until the window itself is resized.
    const resizeObserver = new ResizeObserver(() => map.resize());
    resizeObserver.observe(containerRef.current);

    return () => {
      resizeObserver.disconnect();
      map.remove();
      mapRef.current = null;
      overlayRef.current = null;
    };
  }, []);

  // Account-node pins, rendered via deck.gl instead of DOM markers. The
  // "Hot" pulse ring is preserved as an animated second layer, matching the
  // original CSS keyframe's 2s cycle, and is skipped under
  // prefers-reduced-motion (same convention as tokens.css).
  useEffect(() => {
    const overlay = overlayRef.current;
    if (!overlay) return;

    function buildLayers(pulsePhase: number) {
      // A light "backing plate" behind every dot, always lighter than any
      // fill tier (Brazil green, LATAM ash, or plain basemap) so the colored
      // dot on top reads clearly regardless of what's underneath — without
      // this, a dark-green Hot pin all but disappears against the Brazil
      // country fill.
      const halo = new ScatterplotLayer<AccountMapPinDto>({
        id: "account-pins-halo",
        data: pins,
        filled: true,
        stroked: false,
        radiusUnits: "pixels",
        getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
        getRadius: 12,
        getFillColor: [...cssColor("--color-surface"), 235],
      });

      const base = new ScatterplotLayer<AccountMapPinDto>({
        id: "account-pins",
        data: pins,
        pickable: true,
        stroked: true,
        filled: true,
        radiusUnits: "pixels",
        lineWidthUnits: "pixels",
        getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
        getRadius: 9,
        getFillColor: (pin) => cssColor(TEMP_BAND_VAR[pin.temperatureBand ?? "Cold"] ?? "--color-temp-cold"),
        getLineColor: (pin) => (pin.id === selectedAccountId ? cssColor("--color-primary-active") : cssColor("--color-surface")),
        getLineWidth: (pin) => (pin.id === selectedAccountId ? 3 : 2),
        onClick: (info) => {
          if (info.object) onSelectAccountRef.current?.(info.object.id);
        },
        updateTriggers: {
          getLineColor: selectedAccountId,
          getLineWidth: selectedAccountId,
        },
      });

      const hotPins = pins.filter((pin) => pin.temperatureBand === "Hot");
      const hotColor = cssColor("--color-temp-hot");
      const pulse = new ScatterplotLayer<AccountMapPinDto>({
        id: "account-pins-pulse",
        data: hotPins,
        stroked: true,
        filled: false,
        radiusUnits: "pixels",
        lineWidthUnits: "pixels",
        getPosition: (pin) => [pin.coordinate.longitude, pin.coordinate.latitude],
        getRadius: 10 + pulsePhase * 22,
        getLineColor: [...hotColor, Math.round((1 - pulsePhase) * 180)],
        getLineWidth: 2,
      });

      return [halo, pulse, base];
    }

    const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const hasHotPin = pins.some((pin) => pin.temperatureBand === "Hot");

    if (!hasHotPin || reducedMotion) {
      overlay.setProps({ layers: buildLayers(0) });
      return;
    }

    let frame: number;
    const start = performance.now();
    const tick = (now: number) => {
      const phase = ((now - start) % 2000) / 2000;
      overlay.setProps({ layers: buildLayers(phase) });
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);

    return () => cancelAnimationFrame(frame);
  }, [pins, selectedAccountId]);

  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    const pin = pins.find((p) => p.id === selectedAccountId);
    if (!pin) return;

    map.flyTo({
      center: [pin.coordinate.longitude, pin.coordinate.latitude],
      zoom: SELECTED_ZOOM,
      duration: 1200,
      essential: true,
    });
  }, [selectedAccountId, pins]);

  return (
    <div className="brazil-map">
      <div className={`brazil-map__flat${is3D ? " brazil-map__flat--hidden" : ""}`}>
        <div ref={containerRef} className="brazil-map__canvas" />
        {/* deck.gl renders pins to canvas, which isn't natively focusable/
            screen-reader-accessible. This mirrors the same click behavior as a
            real, tabbable, always-in-the-DOM control per pin — hidden until
            focused so it doesn't visually duplicate the canvas dots. */}
        <div className="brazil-map__a11y-pins">
          {pins.map((pin) => (
            <button
              key={pin.id}
              type="button"
              className="brazil-map__a11y-pin"
              aria-label={pin.name}
              aria-pressed={pin.id === selectedAccountId}
              onClick={() => onSelectAccount?.(pin.id)}
            >
              {pin.name}
            </button>
          ))}
        </div>
      </div>
      {has3DLoaded && (
        <div className={`brazil-map__globe${is3D ? " brazil-map__globe--visible" : ""}`} aria-hidden={!is3D}>
          <Brazil3D />
        </div>
      )}
      <div className="brazil-map__3d-hint">Hold ⌃ Control for 3D terrain</div>
    </div>
  );
}
