/**
 * One-off generator, run manually via `npm run generate:map-data`.
 * Not part of the build — its output is committed to the repo:
 *
 *   packages/ui/public/data/world-countries-tiers.geojson
 *   packages/ui/src/design/generated/brazil-outline.ts
 *
 * Both are derived from the same world-atlas topology so the live MapLibre
 * paint layers (Phase 3) and the entry-animation SVG (Phase 2) agree on
 * exactly the same Brazil/LATAM/world geometry.
 */
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";
import type { Topology, GeometryCollection } from "topojson-specification";
import type { Feature, FeatureCollection, Geometry } from "geojson";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));

const BRAZIL_ID = "076";

// Spanish/Portuguese/French-speaking Latin America: Mexico, Central America,
// the Latin Caribbean, and South America minus Brazil. Deliberately excludes
// Anglophone Caribbean (Jamaica, Bahamas, Trinidad, etc.) — not "LATAM" in
// the sense this design uses.
const LATAM_IDS = new Set([
  "484", // Mexico
  "084", // Belize
  "320", // Guatemala
  "340", // Honduras
  "222", // El Salvador
  "558", // Nicaragua
  "188", // Costa Rica
  "591", // Panama
  "192", // Cuba
  "214", // Dominican Republic
  "332", // Haiti
  "170", // Colombia
  "862", // Venezuela
  "328", // Guyana
  "740", // Suriname
  "254", // French Guiana
  "218", // Ecuador
  "604", // Peru
  "068", // Bolivia
  "600", // Paraguay
  "152", // Chile
  "032", // Argentina
  "858", // Uruguay
]);

type Tier = "brazil" | "latam" | "world";

function tierFor(id: string): Tier {
  if (id === BRAZIL_ID) return "brazil";
  if (LATAM_IDS.has(id)) return "latam";
  return "world";
}

const topologyPath = require.resolve("world-atlas/countries-110m.json");
const topology = JSON.parse(readFileSync(topologyPath, "utf-8")) as Topology;
const countriesObject = topology.objects.countries as GeometryCollection;

const countriesFC = feature(topology, countriesObject) as unknown as FeatureCollection<
  Geometry,
  { name: string }
>;

// --- 1. Tiered GeoJSON for the live MapLibre map (Phase 3) ---------------

const tieredFC: FeatureCollection<Geometry, { name: string; tier: Tier }> = {
  type: "FeatureCollection",
  features: countriesFC.features.map((f) => {
    const id = String((f as Feature & { id?: string | number }).id ?? "");
    return {
      ...f,
      properties: { name: f.properties?.name ?? "", tier: tierFor(id) },
    };
  }),
};

const dataDir = resolve(__dirname, "../public/data");
mkdirSync(dataDir, { recursive: true });
writeFileSync(resolve(dataDir, "world-countries-tiers.geojson"), JSON.stringify(tieredFC));

// --- 2. Precomputed SVG paths for the entry-animation silhouette (Phase 2) ---

const brazilFeature = countriesFC.features.find(
  (f) => String((f as Feature & { id?: string | number }).id ?? "") === BRAZIL_ID,
);
if (!brazilFeature) throw new Error("Brazil feature not found in world-atlas topology");

const latamFeatures = countriesFC.features.filter(
  (f) => LATAM_IDS.has(String((f as Feature & { id?: string | number }).id ?? "")),
);
const worldFeatures = countriesFC.features.filter((f) => {
  const id = String((f as Feature & { id?: string | number }).id ?? "");
  return id !== BRAZIL_ID && !LATAM_IDS.has(id);
});

const VIEWBOX_SIZE = 800;
const VIEWBOX_MARGIN = 90;

// Mercator, fit to Brazil's own bounds — matches the projection family
// MapLibre itself uses, so the intro silhouette and the live map read as
// the same shape rather than two different projections of "Brazil".
const projection = geoMercator().fitExtent(
  [
    [VIEWBOX_MARGIN, VIEWBOX_MARGIN],
    [VIEWBOX_SIZE - VIEWBOX_MARGIN, VIEWBOX_SIZE - VIEWBOX_MARGIN],
  ],
  brazilFeature,
);
const path = geoPath(projection);

function combinedPath(features: Feature[]): string {
  return path({ type: "FeatureCollection", features }) ?? "";
}

const brazilPath = combinedPath([brazilFeature]);
const latamPath = combinedPath(latamFeatures);
const worldPath = combinedPath(worldFeatures);

const outputTs = `// Generated by packages/ui/scripts/generate-map-data.ts — do not hand-edit.
// Re-run \`npm run generate:map-data\` (from packages/ui) to regenerate after
// changing the tier lists in that script.

export const BRAZIL_OUTLINE_VIEWBOX = "0 0 ${VIEWBOX_SIZE} ${VIEWBOX_SIZE}";

export const BRAZIL_OUTLINE_PATH = ${JSON.stringify(brazilPath)};

export const LATAM_OUTLINE_PATH = ${JSON.stringify(latamPath)};

export const WORLD_MASSING_PATH = ${JSON.stringify(worldPath)};
`;

const generatedDir = resolve(__dirname, "../src/design/generated");
mkdirSync(generatedDir, { recursive: true });
writeFileSync(resolve(generatedDir, "brazil-outline.ts"), outputTs);

console.log(`Wrote ${tieredFC.features.length} tiered country features to public/data/world-countries-tiers.geojson`);
console.log("Wrote src/design/generated/brazil-outline.ts");
