import { crc32, deflateRawSync } from "node:zlib";
import { describe, expect, it } from "vitest";
import { looksLikePipelineCsv, parseCsv, validatePipelineCsvRows } from "@pulse-brazil/application";
import { xlsxToCsvText } from "./xlsx";

/**
 * Fixtures are built here rather than committed: real Salesforce exports are
 * business data this repo deliberately never stores (see .gitignore), and a
 * hand-written workbook makes the Salesforce-report quirks under test —
 * preamble block, spacer columns, sort glyphs, Subtotal/Count rows, Excel
 * date serials, percent-as-fraction — visible instead of hidden in a binary.
 */

const isPipelineHeader = (headers: string[]) => looksLikePipelineCsv(headers);

function zip(entries: { name: string; text: string }[]): ArrayBuffer {
  const locals: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    const name = Buffer.from(entry.name, "utf8");
    const uncompressed = Buffer.from(entry.text, "utf8");
    const compressed = deflateRawSync(uncompressed);

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(8, 8); // deflate
    local.writeUInt32LE(crc32(uncompressed), 14);
    local.writeUInt32LE(compressed.length, 18);
    local.writeUInt32LE(uncompressed.length, 22);
    local.writeUInt16LE(name.length, 26);

    const header = Buffer.alloc(46);
    header.writeUInt32LE(0x02014b50, 0);
    header.writeUInt16LE(20, 4);
    header.writeUInt16LE(20, 6);
    header.writeUInt16LE(8, 10);
    header.writeUInt32LE(crc32(uncompressed), 16);
    header.writeUInt32LE(compressed.length, 20);
    header.writeUInt32LE(uncompressed.length, 24);
    header.writeUInt16LE(name.length, 28);
    header.writeUInt32LE(offset, 42);

    locals.push(local, name, compressed);
    central.push(header, name);
    offset += local.length + name.length + compressed.length;
  }

  const centralBuffer = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBuffer.length, 12);
  end.writeUInt32LE(offset, 16);

  const zipped = Buffer.concat([...locals, centralBuffer, end]);
  return zipped.buffer.slice(zipped.byteOffset, zipped.byteOffset + zipped.byteLength) as ArrayBuffer;
}

/** styleIndex 1 = date (builtin 14), 2 = percent (builtin 9), 3 = custom currency, 0 = General. */
function workbook(sheetRows: string, sharedStrings: string[] = []): ArrayBuffer {
  return zip([
    {
      name: "xl/workbook.xml",
      text: `<workbook><workbookPr date1904="false"/><sheets><sheet name="Open Brazil Pipeline" r:id="rId3" sheetId="1"/></sheets></workbook>`,
    },
    {
      name: "xl/_rels/workbook.xml.rels",
      text: `<Relationships><Relationship Id="rId3" Target="worksheets/sheet1.xml"/></Relationships>`,
    },
    {
      name: "xl/sharedStrings.xml",
      text: `<sst>${sharedStrings.map((value) => `<si><t>${value}</t></si>`).join("")}</sst>`,
    },
    {
      name: "xl/styles.xml",
      text:
        `<styleSheet><numFmts><numFmt numFmtId="164" formatCode="&quot;R$&quot;#,##0.00"/></numFmts>` +
        `<cellXfs count="4"><xf numFmtId="0"/><xf numFmtId="14"/><xf numFmtId="9"/><xf numFmtId="164"/></cellXfs></styleSheet>`,
    },
    { name: "xl/worksheets/sheet1.xml", text: `<worksheet><sheetData>${sheetRows}</sheetData></worksheet>` },
  ]);
}

const inline = (ref: string, value: string) => `<c r="${ref}" t="inlineStr"><is><t>${value}</t></is></c>`;
const shared = (ref: string, index: number) => `<c r="${ref}" t="s"><v>${index}</v></c>`;
const number = (ref: string, value: number, style = 0) => `<c r="${ref}" s="${style}"><v>${value}</v></c>`;

const PIPELINE_HEADERS = [
  "Opportunity Owner",
  "Account Name",
  "Opportunity Name",
  "Stage",
  "Fiscal Period",
  "Amount",
  "Expected Revenue",
  "Probability (%)",
  "Age",
  "Revenue Live Date",
  "Next Step Summary",
  "Lead Source",
  "Type",
  "Owner Region",
];

/**
 * A Salesforce "formatted report" export: title and Filtered By preamble,
 * an empty spacer column A, a sort arrow on the sorted header, grouping
 * Subtotal/Count rows between the data, and a Grand Totals row at the end.
 * Headers land in B..O, so column A and the trailing spacer must both drop.
 */
const SALESFORCE_REPORT_SHEET = [
  `<row r="1"><c r="A1" s="1"/></row>`,
  `<row r="2">${inline("B2", "Open Brazil Pipeline All Time")}</row>`,
  `<row r="3">${inline("B3", "As of 2026-07-13 12:31:43 Greenwich Mean Time/GMT • Generated by Alex Curtin")}</row>`,
  `<row r="4"/>`,
  `<row r="5">${inline("B5", "Filtered By")}</row>`,
  `<row r="6">${inline("B6", "Show: All opportunities")}</row>`,
  `<row r="7"/>`,
  `<row r="8">${inline("B8", "Opportunity Owner  ↑")}${PIPELINE_HEADERS.slice(1)
    .map((header, index) => inline(String.fromCharCode(67 + index) + "8", header))
    .join("")}${inline("P8", "")}</row>`,
  `<row r="9">${shared("B9", 0)}${shared("C9", 1)}${inline("D9", "BNP Paribas AM Brazil - OR")}${inline("E9", "Live")}` +
    `${inline("F9", "Q1-2026")}${number("G9", 48480, 3)}${number("H9", 48480, 3)}${number("I9", 1, 2)}` +
    `${number("J9", 145)}${number("K9", 46035, 1)}${inline("N9", "5 - New Client, New Product")}${inline("O9", "UK")}</row>`,
  `<row r="10">${inline("D10", "Subtotal")}${inline("E10", "Sum")}${number("H10", 48480, 3)}</row>`,
  `<row r="11">${inline("E11", "Count")}${number("F11", 1)}</row>`,
  `<row r="12">${shared("B12", 0)}${shared("C12", 2)}${inline("D12", "Vortx - TA")}${inline("E12", "Signed")}` +
    `${inline("F12", "Q3-2026")}${number("G12", 27000, 3)}${number("H12", 24300, 3)}${number("I12", 0.9, 2)}` +
    `${number("J12", 1034)}${number("K12", 46254, 1)}${inline("L12", "Vortx said &quot;wait&quot;, then paused")}` +
    `${inline("N12", "5 - New Client, New Product")}${inline("O12", "UK")}</row>`,
  `<row r="13">${inline("B13", "Grand Totals")}${number("H13", 72780, 3)}</row>`,
].join("");

describe("xlsxToCsvText", () => {
  it("converts a Salesforce formatted pipeline report into importable CSV", async () => {
    const buffer = workbook(SALESFORCE_REPORT_SHEET, ["Nelson Pereira", "BNP Paribas Asset Management Brazil", "Vórtx"]);

    const csvText = await xlsxToCsvText(buffer, isPipelineHeader);
    const { headers, rows } = parseCsv(csvText);

    expect(headers).toEqual(PIPELINE_HEADERS);
    expect(looksLikePipelineCsv(headers)).toBe(true);
    expect(rows).toHaveLength(2);
  });

  it("drops the report's grouping rows rather than importing them as deals", async () => {
    const buffer = workbook(SALESFORCE_REPORT_SHEET, ["Nelson Pereira", "BNP Paribas Asset Management Brazil", "Vórtx"]);

    const { rows } = parseCsv(await xlsxToCsvText(buffer, isPipelineHeader));

    expect(rows.map((row) => row["Account Name"])).toEqual(["BNP Paribas Asset Management Brazil", "Vórtx"]);
  });

  it("renders Excel date serials and percentages the way the pipeline validator expects", async () => {
    const buffer = workbook(SALESFORCE_REPORT_SHEET, ["Nelson Pereira", "BNP Paribas Asset Management Brazil", "Vórtx"]);

    const { rows } = parseCsv(await xlsxToCsvText(buffer, isPipelineHeader));

    expect(rows[0]?.["Revenue Live Date"]).toBe("13/01/2026");
    expect(rows[0]?.["Probability (%)"]).toBe("100");
    expect(rows[1]?.["Probability (%)"]).toBe("90");
    expect(rows[0]?.["Amount"]).toBe("48480");
  });

  it("preserves accented names and quoted text through the CSV round trip", async () => {
    const buffer = workbook(SALESFORCE_REPORT_SHEET, ["Nelson Pereira", "BNP Paribas Asset Management Brazil", "Vórtx"]);

    const { rows } = parseCsv(await xlsxToCsvText(buffer, isPipelineHeader));

    expect(rows[1]?.["Account Name"]).toBe("Vórtx");
    expect(rows[1]?.["Next Step Summary"]).toBe('Vortx said "wait", then paused');
  });

  it("produces rows the existing pipeline validator accepts unchanged", async () => {
    const buffer = workbook(SALESFORCE_REPORT_SHEET, ["Nelson Pereira", "BNP Paribas Asset Management Brazil", "Vórtx"]);

    const { rows } = parseCsv(await xlsxToCsvText(buffer, isPipelineHeader));
    const { valid, invalid } = validatePipelineCsvRows(rows);

    expect(invalid).toEqual([]);
    expect(valid).toHaveLength(2);
    expect(valid[0]?.amount).toBe(48480);
    expect(valid[0]?.probabilityPercent).toBe(100);
    expect(valid[1]?.revenueLiveDate?.toISOString()).toBe("2026-08-20T00:00:00.000Z");
    expect(valid[1]?.expectedRevenue).toBe(24300);
  });

  it("reads a plain flat sheet whose header is already the first row", async () => {
    const flat = [
      `<row r="1">${PIPELINE_HEADERS.map((header, index) => inline(String.fromCharCode(65 + index) + "1", header)).join("")}</row>`,
      `<row r="2">${inline("A2", "Nelson Pereira")}${inline("B2", "XP")}${inline("C2", "XP - TA")}${inline("D2", "Qualified")}` +
        `${inline("E2", "Q2-2026")}${number("F2", 55200)}${number("G2", 11040)}${number("H2", 20)}</row>`,
    ].join("");

    const { headers, rows } = parseCsv(await xlsxToCsvText(workbook(flat), isPipelineHeader));

    expect(headers).toEqual(PIPELINE_HEADERS);
    expect(rows).toHaveLength(1);
    expect(validatePipelineCsvRows(rows).valid[0]?.opportunityName).toBe("XP - TA");
  });

  it("reports a readable error instead of importing a workbook it doesn't recognise", async () => {
    const unrelated = [
      `<row r="1">${inline("A1", "Region")}${inline("B1", "Headcount")}${inline("C1", "Office")}</row>`,
      `<row r="2">${inline("A2", "Sudeste")}${number("B2", 12)}${inline("C2", "Sao Paulo")}</row>`,
    ].join("");

    await expect(xlsxToCsvText(workbook(unrelated), isPipelineHeader)).rejects.toThrow(
      /doesn't match either import format\. Columns found: Region, Headcount, Office/,
    );
  });

  /**
   * The real miss reported from production (2026-08-24): a Salesforce
   * *summary* report pivots Stage across the columns and holds only
   * "Sum of ..." / "Record Count" aggregates. The opportunities are not in
   * the file, so the only useful response is to name the report type.
   */
  it("names a Salesforce summary report rather than blaming a missing header row", async () => {
    const matrix = [
      `<row r="1">${inline("B1", "Open Brazil Opportunities this FY")}</row>`,
      `<row r="2">${inline("B2", "Stage →")}${inline("D2", "Prospect")}${inline("G2", "Subtotal")}${inline("J2", "Qualified")}</row>`,
      `<row r="3">${inline("B3", "Revenue Live Date  ↑")}${inline("D3", "Sum of Amount")}${inline("E3", "Record Count")}</row>`,
      `<row r="4">${inline("B4", "May 2026")}${number("D4", 55200)}${number("E4", 1)}</row>`,
    ].join("");

    await expect(xlsxToCsvText(workbook(matrix), isPipelineHeader)).rejects.toThrow(
      /is a Salesforce summary report .* Tabular \(details\) format/s,
    );
  });

  it("names the missing column when a sheet is nearly a pipeline export", async () => {
    // A real tabular opportunity export that carries Amount but no Expected Revenue.
    const nearMiss = [
      `<row r="1">${inline("A1", "Account Name  ↑")}${inline("B1", "Opportunity Name")}${inline("C1", "Stage")}${inline("D1", "Amount")}${inline("E1", "Product")}</row>`,
      `<row r="2">${inline("A2", "Apex Group (Brazil)")}${inline("B2", "Apex Brazil - local TA")}${inline("C2", "Qualified")}${number("D2", 18000)}${inline("E2", "Order Routing")}</row>`,
    ].join("");

    const explain = (headers: string[]) => {
      const missing = headers.some((header) => header.toLowerCase() === "opportunity name")
        ? ["Expected Revenue"]
        : [];
      return missing.length > 0 ? `missing: ${missing.join(", ")}` : undefined;
    };

    await expect(xlsxToCsvText(workbook(nearMiss), isPipelineHeader, explain)).rejects.toThrow(/missing: Expected Revenue/);
  });
});
